// <auto-generated />
using System;
using HighPerformanceFraudDetectionSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HighPerformanceFraudDetectionSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112105800_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FraudRuleTransaction", b =>
                {
                    b.Property<int>("FraudRulesFraudRuleId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionsTransactionId")
                        .HasColumnType("int");

                    b.HasKey("FraudRulesFraudRuleId", "TransactionsTransactionId");

                    b.HasIndex("TransactionsTransactionId");

                    b.ToTable("FraudRuleTransaction");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.FraudCase", b =>
                {
                    b.Property<int>("FraudCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FraudCaseId"));

                    b.Property<DateTime>("DetectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FraudRuleId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("FraudCaseId");

                    b.HasIndex("FraudRuleId");

                    b.HasIndex("TransactionId");

                    b.ToTable("FraudCases");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.FraudRule", b =>
                {
                    b.Property<int>("FraudRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FraudRuleId"));

                    b.Property<string>("ConditionExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FraudRuleId");

                    b.ToTable("FraudRules");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.TransactionFraudRule", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("FraudRuleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId", "FraudRuleId");

                    b.HasIndex("FraudRuleId");

                    b.ToTable("TransactionFraudRules");
                });

            modelBuilder.Entity("FraudRuleTransaction", b =>
                {
                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.FraudRule", null)
                        .WithMany()
                        .HasForeignKey("FraudRulesFraudRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionsTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.FraudCase", b =>
                {
                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.FraudRule", "FraudRule")
                        .WithMany("FraudCases")
                        .HasForeignKey("FraudRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.Transaction", "Transaction")
                        .WithMany("FraudCases")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FraudRule");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.Transaction", b =>
                {
                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.TransactionFraudRule", b =>
                {
                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.FraudRule", "FraudRule")
                        .WithMany("TransactionFraudRules")
                        .HasForeignKey("FraudRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighPerformanceFraudDetectionSystem.Models.Transaction", "Transaction")
                        .WithMany("TransactionFraudRules")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FraudRule");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.FraudRule", b =>
                {
                    b.Navigation("FraudCases");

                    b.Navigation("TransactionFraudRules");
                });

            modelBuilder.Entity("HighPerformanceFraudDetectionSystem.Models.Transaction", b =>
                {
                    b.Navigation("FraudCases");

                    b.Navigation("TransactionFraudRules");
                });
#pragma warning restore 612, 618
        }
    }
}
